### ISSUE TITLE
Italic format

### ISSUE THREAD

**Issue by ForionOG** [FaeWulf/item-rename#1]
Hi i really like this mod but for some reason when i rename my items it will always be in italic format i tried using different & codes but that hasn't helped me. any way to fix this?
Thanks in advance!

**Comment by FaeWulf** [comment]
Thank you for open this issue!
Usually you can prevent italic by adding `&r` before all your format! But minecraft it self doesn't like this!
I encountered this issue from 1-2 days ago and made a fix but forgot to push and update the mod!
 I will try to update it asap!
 As expect, you will prevent italic by using `&r`.

**Comment by FaeWulf** [comment]
Updated!
https://modrinth.com/mod/faewulf-itemrename/version/1.0.1+1.21
